dashboard/urls.py
from django.urls import path

from . import views


urlpatterns = [
    # http://www.domena.com/details/2
    path('details/<int:pk>', views.details, name='details'),
    path('', views.dashboard, name='dashboard'),
]

image_processor/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.upload_image, name='upload_image'),
]

project_core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('image-upload/', include(('image_processor.urls', 'image_processor'), namespace='image_processor')),
    path('', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
]

dashboard/models.py
from django.db import models

# Create your models here.

image_processor/models.py
import uuid

from django.db import models
from django.utils import timezone

# Create your models here.
class PeopleCounter(models.Model):
    original_file = models.ImageField(upload_to=f'uploads/original/{uuid.uuid4()}.jpg')
    yolo_processed_file = models.ImageField(upload_to=f'uploads/yolo/{uuid.uuid4()}.jpg',
                                            null=True,
                                            blank=True)
    hog_processed_file = models.ImageField(upload_to=f'uploads/hog/{uuid.uuid4()}.jpg',
                                           null=True,
                                           blank=True)

    yolo_counter = models.IntegerField(null=True, blank=True)
    hog_counter = models.IntegerField(null=True, blank=True)

    processed_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'People Counter {self.pk}'

dashboard/views.py
from django.shortcuts import render

# Create your views here.
def dashboard(request):
    return render(request, 'dashboard/dashboard.html')

def details(request, pk):
    return render(request, 'dashboard/details.html')

image_processor/views.py
from django.shortcuts import redirect, render

from .open_cv_processor.image_processor_hog import detect_people_hog
from .open_cv_processor.image_processor_yolo import detect_people_yolo
from .models import PeopleCounter

# Create your views here.
def upload_image(request):
    if request.method == "POST" and request.FILES.get('image'):
        uploaded_file = request.FILES['image']

        people_counter = PeopleCounter()
        people_counter.original_file.save(uploaded_file.name, uploaded_file)
        people_counter.save()

        yolo_file, yolo_counter = detect_people_yolo(people_counter.original_file.path)
        if yolo_file:
            people_counter.yolo_counter = yolo_counter
            people_counter.yolo_processed_file.name = yolo_file

        hog_file, hog_counter = detect_people_hog(people_counter.original_file.path)
        if hog_file:
            people_counter.hog_counter = hog_counter
            people_counter.hog_processed_file.name = hog_file


        people_counter.save()

        return redirect('dashboard:dashboard')
    return render(request, 'image_processor/image-upload.html')

templates/base/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django People Counter - {% block page_title %}{% endblock page_title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    {% block page_css %}{% endblock page_css %}
  </head>
  <body class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'dashboard:dashboard' %}">Dj People Counter</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'image_processor:upload_image' %}">File upload</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <div class="my-3">
        {% block page_content %}{% endblock page_content %}
      </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
    {% block page_js %}{% endblock page_js %}
  </body>
</html>

templates/dashboard/dashboard.html
{% extends 'base/base.html' %}

{% block page_content %}
    <h1>Dashboard is wokring!</h1>
{% endblock page_content %}

templates/dashboard/details.html
{% extends 'base/base.html' %}

{% block page_content %}
    <h1>Details is wokring!</h1>
{% endblock page_content %}

templates/image_processor/image-upload.html
{% extends 'base/base.html' %}

{% block page_css %}

{% endblock page_css %}

{% block page_content %}
    <h1>Upload and process image!</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="mb-3">
            <label for="image" class="form-label">
                Ucitajte image file koji zelite analizirati
            </label>
            <input class="form-control"
                    accept="image/*"
                    name="image"
                    type="file"
                    id="image"
                    required>
        </div>

        <button type="submit" class="btn btn-success">Upload and process</button>
    </form>
{% endblock page_content %}

{% block page_js %}
{% endblock page_js %}